# Generated by Django 4.1.5 on 2024-02-27 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OFFER_ITEM', to='Products.item')),
            ],
        ),
    ]
