# Generated by Django 4.1.5 on 2024-02-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_offers_options_offers_offer_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='discount_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
