# Generated by Django 4.1.5 on 2024-03-06 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_offers_discount_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='offer_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='Products.item'),
        ),
    ]
